#!/usr/bin/env bash

# Create a regex for a conventional commit.
convetional_commit_regex="^(build|chore|ci|docs|feat|fix|performance|refactor|revert|test)(\([a-z \-]+\))?!?: .+$"

# Get the commit message (the parameter we're given is just the path to the
# temporary file which holds the message).
commit_message=$(cat "$1")

# Check the message, if we match, all good baby.
if [[ "$commit_message" =~ $convetional_commit_regex ]]; then
   echo -e "\e[32mCommit message meets Conventional Commit standards...\e[0m"
   exit 0
fi

# Uh-oh, this is not a conventional commit, show an example and link to the spec.
echo -e "\e[31mcommit message does not meet our Conventional Commit standard\e[0m"
echo -e "\e[47m\e[1;94mExamples of valid messages: \e[0m"
echo -e "  \e[32mfeat(login): add the 'remember me' button\e[0m"
echo -e "  \e[32mfix(login): fixed the 'remember me' button\e[0m"
exit 1