name: 'Release'
on:
  release:
  push:
  workflow_dispatch:
  
jobs:
  parse:
    runs-on: ubuntu-latest
    steps:
    - run: echo "GITHUB_REF- $GITHUB_REF"
    - run: echo "GITHUB_REF_NAME- $GITHUB_REF_NAME"
